version: '3'

services:
  salehproject-:
    image: ghcr.io/salehabujazar/salehproject-:latest 
    deploy:
    labels: [com.centurylinklabs.watchtower.enable=true]
    container_name: project-deep-2023-24
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GNEWS_API_KEY=your_api_key_here
    command: npm start
