version: '3'

services:
  app:
    image: ghcr.io/salehabujazar/salehproject-:latest 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GNEWS_API_KEY=your_api_key_here
    command: npm start
