name: Manual Docker Image CI

permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker Metadata action
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          # List of Docker images to use as base name for tags
          images: ghcr.io/${{ github.repository }}
          # List of tags as key-value pair attributes
          tags: |
            type=ref,event=branch,pattern={{branch}}-{{sha}}
            type=ref,event=pr,pattern=pr-{{pr}}-{{sha}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: |
            latest=true

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
